name: Create Tag for Release

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Get version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r .version < package.json)
        echo "::set-output name=VERSION::$VERSION"

    - name: Create GitHub Tag
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git tag -a "v$VERSION" -m "Release version $VERSION"
        git push origin "v$VERSION"
